version: "3"
services:
  # Website instance
  website:
    depends_on:
      - "migration"
    build:
      context: "../src"
      dockerfile: "PersonalWebsite/Dockerfile"
    environment:
      ASPNETCORE_ENVIRONMENT: "Production"
    ports:
      - "80:80"
      - "443:443"
    expose:
      - "80"
      - "443"
    network_mode: "bridge"
    restart: "always"
  # Migrations
  migration:
    build:
      context: "../src"
      dockerfile: "PersonalWebsite/Migrations/Dockerfile"
    environment:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      ASPNETCORE_ENVIRONMENT: "Production"
    network_mode: "bridge"
