version: "3"
services:
  # Development-only database (DB is in cloud in production)
  database:
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "DevelopmentPassword0_2"
    image: "microsoft/mssql-server-linux:latest"
    ports:
      - 1433:1433
    expose:
      - 1433

  # Website instance
  website:
    depends_on:
      - "migration"
      - "database"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
    volumes:
      - "../nginx/website_development.conf:/etc/nginx/conf.d/website_development.conf"
      
  # Migrations
  migration:
    depends_on:
      - "database"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
