# This actions runs the dotnet and js tests

name: Test the app

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop, master ]

env:
  APP_PATH: 'src/PersonalWebsite'
  NODE_VERSION: '14.x'
  DOTNET_VERSION: '5.0.100'
  
jobs:
  run-tests:
    name: Run tests
    runs-on: [ubuntu-18.04]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: Use .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    - name: Test 
      run: |
        cd ${{ env.APP_PATH }} # go to the source code folder
        npm ci
        npm run build --if-present
        npm run test --if-present
        dotnet test
